### ISSUE TITLE
slice() can invalidate primary keys

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#151]
if positive indexes are repeated.

**Comment by TSchiefer** [comment]
I was looking into this a little, but it isn't trivial, since the user can give slice-conditions which involve columns of the table in question.

I looked a bit into the {dplyr}-code, but couldn't easily find a function, that takes a table and the condition and returns the indices. Would you have a pointer as to how to get the indices from the condition? 

Alternatively we could of course perform a check after applying slice in case the original table had a PK. But this hardly seems like a viable solution.

We could also restrict the user to only provide integer vectors (or numeric, as this is for some reason also allowed by `slice()`, not sure why).

**Comment by krlmlr** [comment]
Slice takes a vector of indexes, using standard evaluation?

**Comment by TSchiefer** [comment]
Sounds good to me, I will implement it in this way

**Comment by TSchiefer** [comment]
Are you OK with not accepting numeric vectors?
